# Dependencies
highlighter:      rouge

# Config
gems: [jekyll-gist,jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Northwestern Digital Frameworks
tagline:          'Summer quarter 2016'
description:      'A high level view of digital journalism practice, summer 2016 edition.'
url:              http://digitalframeworks.github.io
baseurl:          /

author:
  name:           'David Eads'
  url:            https://twitter.com/eads

paginate:         15

exclude: [node_modules]

sass:
  sass_dir: _sass
  style: compressed

# Custom vars
navlinks:
- url: https://nwudigitalframeworks.slack.com/messages/general/
  title: Slack
- url: mailto:davideads@gmail.com
  title: Email
